config/routes.rb
Rails.application.routes.draw do
  resources :drink_users
  resources :drinks
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drink.rb
class Drink < ApplicationRecord

  has_many :drink_users
  has_many :users, through: :drink_users

end

app/models/drink_user.rb
class DrinkUser < ApplicationRecord

  belongs_to :user, optional: true
  belongs_to :drink, optional: true

end

app/models/user.rb
class User < ApplicationRecord

  has_many :drink_users
  has_many :drinks, through: :drink_users
  accepts_nested_attributes_for :drink_users, allow_destroy: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/drink_users_controller.rb
class DrinkUsersController < ApplicationController
  before_action :set_drink_user, only: [:show, :edit, :update, :destroy]

  # GET /drink_users
  # GET /drink_users.json
  def index
    @drink_users = DrinkUser.all
  end

  # GET /drink_users/1
  # GET /drink_users/1.json
  def show
  end

  # GET /drink_users/new
  def new
    @drink_user = DrinkUser.new
  end

  # GET /drink_users/1/edit
  def edit
  end

  # POST /drink_users
  # POST /drink_users.json
  def create
    @drink_user = DrinkUser.new(drink_user_params)

    respond_to do |format|
      if @drink_user.save
        format.html { redirect_to @drink_user, notice: 'Drink user was successfully created.' }
        format.json { render :show, status: :created, location: @drink_user }
      else
        format.html { render :new }
        format.json { render json: @drink_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drink_users/1
  # PATCH/PUT /drink_users/1.json
  def update
    respond_to do |format|
      if @drink_user.update(drink_user_params)
        format.html { redirect_to @drink_user, notice: 'Drink user was successfully updated.' }
        format.json { render :show, status: :ok, location: @drink_user }
      else
        format.html { render :edit }
        format.json { render json: @drink_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drink_users/1
  # DELETE /drink_users/1.json
  def destroy
    @drink_user.destroy
    respond_to do |format|
      format.html { redirect_to drink_users_url, notice: 'Drink user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drink_user
      @drink_user = DrinkUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drink_user_params
      params.fetch(:drink_user, {})
    end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :set_drink, only: [:show, :edit, :update, :destroy]

  # GET /drinks
  # GET /drinks.json
  def index
    @drinks = Drink.all
  end

  # GET /drinks/1
  # GET /drinks/1.json
  def show
  end

  # GET /drinks/new
  def new
    @drink = Drink.new
  end

  # GET /drinks/1/edit
  def edit
  end

  # POST /drinks
  # POST /drinks.json
  def create
    @drink = Drink.new(drink_params)

    respond_to do |format|
      if @drink.save
        format.html { redirect_to @drink, notice: 'Drink was successfully created.' }
        format.json { render :show, status: :created, location: @drink }
      else
        format.html { render :new }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drinks/1
  # PATCH/PUT /drinks/1.json
  def update
    respond_to do |format|
      if @drink.update(drink_params)
        format.html { redirect_to @drink, notice: 'Drink was successfully updated.' }
        format.json { render :show, status: :ok, location: @drink }
      else
        format.html { render :edit }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drinks/1
  # DELETE /drinks/1.json
  def destroy
    @drink.destroy
    respond_to do |format|
      format.html { redirect_to drinks_url, notice: 'Drink was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drink
      @drink = Drink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drink_params
      params.require(:drink).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @drinks = Drink.all
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, drink_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drink_users_helper.rb
module DrinkUsersHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/drink_users/_form.html.haml
= form_for(drink_user) do |f|
  - if drink_user.errors.any?
    #error_explanation
      %h2
        = pluralize(drink_user.errors.count, "error")
        prohibited this drink_user from being saved:
      %ul
        - drink_user.errors.full_messages.each do |message|
          %li= message
  .actions
    = f.submit

app/views/drink_users/edit.html.haml
%h1 Editing Drink User
= render 'form', drink_user: @drink_user
= link_to 'Show', @drink_user
|
= link_to 'Back', drink_users_path

app/views/drink_users/index.html.haml
%p#notice= notice
%h1 Drink Users
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @drink_users.each do |drink_user|
      %tr
        %td= link_to 'Show', drink_user
        %td= link_to 'Edit', edit_drink_user_path(drink_user)
        %td= link_to 'Destroy', drink_user, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Drink User', new_drink_user_path

app/views/drink_users/new.html.haml
%h1 New Drink User
= render 'form', drink_user: @drink_user
= link_to 'Back', drink_users_path

app/views/drink_users/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_drink_user_path(@drink_user)
|
= link_to 'Back', drink_users_path

app/views/drinks/_form.html.haml
= form_for(drink) do |f|
  - if drink.errors.any?
    #error_explanation
      %h2
        = pluralize(drink.errors.count, "error")
        prohibited this drink from being saved:
      %ul
        - drink.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit

app/views/drinks/edit.html.haml
%h1 Editing Drink
= render 'form', drink: @drink
= link_to 'Show', @drink
|
= link_to 'Back', drinks_path

app/views/drinks/index.html.haml
%p#notice= notice
%h1 Drinks
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @drinks.each do |drink|
      %tr
        %td= drink.name
        %td= link_to 'Show', drink
        %td= link_to 'Edit', edit_drink_path(drink)
        %td= link_to 'Destroy', drink, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Drink', new_drink_path

app/views/drinks/new.html.haml
%h1 New Drink
= render 'form', drink: @drink
= link_to 'Back', drinks_path

app/views/drinks/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_drink_path(@drink)
|
= link_to 'Back', drinks_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SampleCollectionCheckBoxes
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/users/_form.html.haml
= form_for(user) do |f|
  - if user.errors.any?
    #error_explanation
      %h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name

    = f.collection_check_boxes :drink_ids, @drinks, :id, :name, include_hidden: false do |b|
      = b.label { b.check_box + b.text }

  .actions
    = f.submit

app/views/users/edit.html.haml
%h1 Editing User
= render 'form', user: @user
= link_to 'Show', @user
|
= link_to 'Back', users_path

app/views/users/index.html.haml
%p#notice= notice
%h1 Users
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New User

= render 'form', user: @user
= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @user.name
  に買わないといけないモノ

- @user.drinks.each do |drink|
  %p
    = drink.name

= link_to 'Edit', edit_user_path(@user)
|
= link_to 'Back', users_path